gui:
  theme:
    activeBorderColor:
      - "#33b1ff"
      - bold
    inactiveBorderColor:
      - "#42be65"
    searchingActiveBorderColor:
      - "#be95ff"
      - bold
    optionsTextColor:
      - "#dde1e6"
    selectedLineBgColor:
      - "#303030"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#dde1e6"
    cherryPickedCommitBgColor:
      - "#be95ff"
    markedBaseCommitFgColor:
      - "#be95ff"
    markedBaseCommitBgColor:
      - "#ee5396"
    unstagedChangesColor:
      - "#ee5396"
    defaultFgColor:
      - "#f2f4f8"
  skipDiscardChangeWarning: true
